"""Option B (PROBLEMS.md §243): every store through `db.connect`.

* With no DATABASE_URL nothing changes: a store gets a sqlite3 connection.
* With one, a store's SQLite is translated to Postgres - and the parts that
  could silently change meaning (REAL timestamps, LIKE's case, INSERT OR
  REPLACE, SQLite's self-numbering row ids) are pinned here.
* Staging reaches its own private database and nothing else (the owner's
  amendment to zero-spend-staging): libpq's sockets are invisible to the
  network guard, so `db.connect` enforces it, and the guard allows exactly
  that one address for anything that does go through Python's sockets.

The round-trip tests at the bottom need a Postgres (CI's Postgres job sets
DATABASE_URL); everything above them runs anywhere.
"""
from __future__ import annotations

import os
import sqlite3
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import db  # noqa: E402
import spend_guard  # noqa: E402


def sql(statement: str, named: bool = False) -> str:
    return db.translate(statement, named)[0]


def test_without_a_database_url_a_store_gets_sqlite(monkeypatch, tmp_path):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    conn = db.connect(str(tmp_path / "x.db"), timeout=5.0, isolation_level=None)
    assert isinstance(conn, sqlite3.Connection)
    assert db.report() == {"backend": "sqlite"}


def test_timestamps_keep_their_precision():
    # Postgres' REAL is four bytes: an epoch time would round by minutes.
    assert "DOUBLE PRECISION" in sql("CREATE TABLE t (at REAL NOT NULL)")
    assert " REAL" not in sql("CREATE TABLE t (at REAL NOT NULL)")


def test_a_sqlite_row_id_still_numbers_itself():
    for ddl in ("CREATE TABLE t (id INTEGER PRIMARY KEY, x TEXT)",
                "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT)"):
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql(ddl)


def test_like_ignores_case_as_sqlite_did():
    assert sql("SELECT 1 FROM t WHERE handle LIKE ?") == \
        "SELECT 1 FROM t WHERE handle ILIKE %s"
    assert "NOT ILIKE 'g:%%'" in sql("SELECT 1 FROM t WHERE r NOT LIKE 'g:%'")
    assert sql("SELECT x FROM t ORDER BY name COLLATE NOCASE") == \
        "SELECT x FROM t ORDER BY lower(name)"


def test_placeholders_and_literals():
    assert sql("SELECT * FROM t WHERE a = ? AND b = ?") == \
        "SELECT * FROM t WHERE a = %s AND b = %s"
    assert sql("SELECT * FROM t WHERE a = :who", named=True) == \
        "SELECT * FROM t WHERE a = %(who)s"
    # A colon in a string literal is text unless the parameters are named.
    assert sql("SELECT 'a:b' FROM t WHERE x = ?") == "SELECT 'a:b' FROM t WHERE x = %s"


def test_a_scalar_max_with_a_call_inside_it():
    assert sql("UPDATE t SET f = MAX(?, CASE WHEN a THEN b ELSE 0 END), e = MAX(e, ?)") == \
        "UPDATE t SET f = GREATEST(%s, CASE WHEN a THEN b ELSE 0 END), e = GREATEST(e, %s)"
    assert sql("SELECT MAX(id), MIN(COALESCE(a, b), 3) FROM t") == \
        "SELECT MAX(id), LEAST(COALESCE(a, b), 3) FROM t"


def test_inserts_that_ignore_or_replace():
    statement, kind, table, columns = db.translate(
        "INSERT OR IGNORE INTO members (gid, user_id) VALUES (?, ?)")
    assert statement.endswith("ON CONFLICT DO NOTHING") and kind == "ignore"
    statement, kind, table, columns = db.translate(
        "INSERT OR REPLACE INTO prefs (user_id, topics) VALUES (?, ?)")
    assert kind == "replace" and table == "prefs" and columns == ("user_id", "topics")
    assert statement.startswith("INSERT INTO prefs")


def test_pragmas():
    assert db.translate("PRAGMA journal_mode=WAL")[1] == "skip"
    assert "information_schema.columns" in sql("PRAGMA table_info(usage)")
    assert "column_name AS name" in sql("PRAGMA table_info(usage)")


def test_each_store_file_is_its_own_schema():
    a = db.schema_for("/data/messages.db")
    assert a.startswith("messages_")
    assert db.schema_for("/data/social.db").split("_")[-1] == a.split("_")[-1]
    assert db.schema_for("/tmp/other/messages.db") != a


def test_the_address_is_read_from_either_form():
    assert db.host_of("postgresql://u:p@dpg-abc-a:5432/fam") == ("dpg-abc-a", 5432)
    assert db.host_of("host=/tmp port=5433 user=postgres") == ("/tmp", 5433)
    assert db.host_of("") == ("", 0)


def test_staging_refuses_a_public_database(monkeypatch):
    monkeypatch.setattr(spend_guard, "enabled", lambda: True)
    monkeypatch.setattr(db, "_resolves_private", lambda host: host == "dpg-private-a")
    db.check_staging_address("postgresql://u:p@dpg-private-a/fam")
    with pytest.raises(db.DatabaseRefused):
        db.check_staging_address("postgresql://u:p@db.example.com/fam")


def test_production_is_not_held_to_staging_s_rule(monkeypatch):
    monkeypatch.setattr(spend_guard, "enabled", lambda: False)
    monkeypatch.setattr(db, "_resolves_private", lambda host: False)
    db.check_staging_address("postgresql://u:p@db.example.com/fam")


def test_the_guard_allows_exactly_the_one_private_database(monkeypatch):
    monkeypatch.setattr(spend_guard, "_DATABASE", {("10.0.0.7", 5432)})
    assert spend_guard._is_local(("10.0.0.7", 5432))
    assert not spend_guard._is_local(("10.0.0.7", 5433)), "another port on it"
    assert not spend_guard._is_local(("10.0.0.8", 5432)), "a neighbour"
    assert not spend_guard._is_local(("93.184.216.34", 443))


@pytest.mark.parametrize("dsn, env", [
    ("postgresql:///fam?host=db.example.com", {}),
    ("postgresql://u@/fam?host=8.8.8.8", {}),
    ("host=10.0.0.7 hostaddr=8.8.8.8 dbname=fam", {}),
    ("hostaddr=8.8.8.8 dbname=fam", {}),
    ("service=prod", {}),
    ("dbname=fam", {"PGHOST": "db.example.com"}),
    ("dbname=fam", {"PGHOSTADDR": "8.8.8.8"}),
    ("host=10.0.0.7,db.example.com dbname=fam", {}),
])
def test_staging_reads_the_address_the_way_libpq_does(monkeypatch, dsn, env):
    """Review fix: only `host=` and the URL's host were read, so a query
    string, hostaddr, a service file or PGHOST could send staging anywhere."""
    for name in ("PGHOST", "PGHOSTADDR", "PGSERVICE", "PGSERVICEFILE", "PGPORT"):
        monkeypatch.delenv(name, raising=False)
    for name, value in env.items():
        monkeypatch.setenv(name, value)
    monkeypatch.setattr(spend_guard, "enabled", lambda: True)
    monkeypatch.setattr(db, "_resolves_private", lambda host: not host or host.startswith("10."))
    with pytest.raises(db.DatabaseRefused):
        db.check_staging_address(dsn)


def test_staging_may_use_its_own_socket_or_private_host(monkeypatch):
    for name in ("PGHOST", "PGHOSTADDR", "PGSERVICE", "PGSERVICEFILE"):
        monkeypatch.delenv(name, raising=False)
    monkeypatch.setattr(spend_guard, "enabled", lambda: True)
    monkeypatch.setattr(db, "_resolves_private", lambda host: not host or host.startswith("10."))
    db.check_staging_address("postgresql://u:p@10.0.0.7:5432/fam")
    db.check_staging_address("postgresql:///fam")
    db.check_staging_address("host=10.0.0.7,10.0.0.8 dbname=fam")


def test_every_connection_path_checks_the_address():
    """Review fix: three connects (has_tables, the admin tracker's two) went
    straight to psycopg and skipped the check."""
    import pathlib

    root = pathlib.Path(__file__).resolve().parent.parent
    offenders = []
    for path in root.glob("*.py"):
        text = path.read_text()
        if "psycopg.connect(" in text and path.name != "db.py":
            offenders.append(path.name)
    assert not offenders, offenders
    source = (root / "db.py").read_text()
    assert source.count("psycopg.connect(") == 2  # the pool's, and raw_connect's
    assert "check_staging_address()" in source.split("def _open")[1].split("def ")[0]
    assert "check_staging_address()" in source.split("def raw_connect")[1].split("def ")[0]


def test_a_literal_is_never_rewritten():
    assert sql("SELECT 1 FROM t WHERE q = 'what?' AND id = ?") == \
        "SELECT 1 FROM t WHERE q = 'what?' AND id = %s"
    assert sql("SELECT 'I like it' FROM t") == "SELECT 'I like it' FROM t"
    assert sql("SELECT ' :y' FROM t WHERE a = :y", named=True) == \
        "SELECT ' :y' FROM t WHERE a = %(y)s"
    assert sql("CREATE TABLE t (n TEXT COLLATE NOCASE)") == "CREATE TABLE t (n TEXT)"


def test_a_public_database_is_not_allowed_by_the_guard(monkeypatch):
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@db.example.com:5432/fam")
    monkeypatch.setattr(db, "_resolves_private", lambda host: False)
    assert spend_guard._database_addresses() == set()


# -------------------------------------------------- against a real Postgres

needs_postgres = pytest.mark.skipif(not db.enabled(),
                                    reason="no DATABASE_URL (CI's Postgres job sets one)")


@needs_postgres
def test_a_replace_is_an_upsert_on_the_key(tmp_path):
    conn = db.connect(str(tmp_path / "prefs.db"))
    conn.execute("CREATE TABLE IF NOT EXISTS prefs (user_id TEXT PRIMARY KEY,"
                 " topics TEXT NOT NULL DEFAULT '', at REAL)")
    conn.execute("INSERT OR REPLACE INTO prefs (user_id, topics, at) VALUES (?, ?, ?)",
                 ("u1", "nfl", 1791600000.25))
    conn.execute("INSERT OR REPLACE INTO prefs (user_id, topics, at) VALUES (?, ?, ?)",
                 ("u1", "nba", 1791600001.75))
    rows = conn.execute("SELECT user_id, topics, at FROM prefs").fetchall()
    assert [tuple(r) for r in rows] == [("u1", "nba", 1791600001.75)]
    assert rows[0]["topics"] == "nba"


def _failed_write_in_a_transaction(conn):
    conn.execute("CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY, x TEXT UNIQUE)")
    conn.execute("BEGIN")
    conn.execute("INSERT INTO t (x) VALUES (?)", ("a",))
    with pytest.raises(sqlite3.IntegrityError):
        conn.execute("INSERT INTO t (x) VALUES (?)", ("a",))
    cur = conn.execute("INSERT INTO t (x) VALUES (?)", ("b",))
    assert cur.lastrowid is not None
    conn.execute("COMMIT")
    return [r[0] for r in conn.execute("SELECT x FROM t ORDER BY x").fetchall()]


@needs_postgres
def test_a_failed_write_is_undone_alone_as_in_sqlite(tmp_path, monkeypatch):
    """Review fix: the failed statement used to roll the whole transaction
    back silently and run the rest in autocommit - `a` was lost."""
    on_postgres = _failed_write_in_a_transaction(
        db.connect(str(tmp_path / "t.db"), isolation_level=None))
    monkeypatch.delenv("DATABASE_URL")
    on_sqlite = _failed_write_in_a_transaction(
        db.connect(str(tmp_path / "t.db"), isolation_level=None))
    assert on_postgres == on_sqlite == ["a", "b"]


@needs_postgres
def test_short_lived_threads_do_not_leak_connections(tmp_path):
    """Review fix: a connection per store per thread was kept forever, and
    provider_usage starts a thread every ten seconds."""
    import threading

    path = str(tmp_path / "usage.db")
    db.connect(path, isolation_level=None).execute(
        "CREATE TABLE IF NOT EXISTS calls (id INTEGER PRIMARY KEY, n INTEGER)")

    def flush():
        db.connect(path, isolation_level=None).execute("INSERT INTO calls (n) VALUES (1)")

    for _ in range(60):
        t = threading.Thread(target=flush)
        t.start()
        t.join()
    stats = db._POOL.stats()
    assert stats["open"] <= db.IDLE_KEPT, stats
    assert db.connect(path).execute("SELECT COUNT(*) FROM calls").fetchone()[0] == 60


@needs_postgres
def test_begin_immediate_still_keeps_out_a_second_writer(tmp_path):
    """Review fix: a check-then-spend inside BEGIN IMMEDIATE (the trending
    bank's budget, the edition's claim) let two writers both pass."""
    import threading
    import time as _time

    path = str(tmp_path / "bank.db")
    setup = db.connect(path, isolation_level=None)
    setup.execute("CREATE TABLE IF NOT EXISTS spend (k TEXT PRIMARY KEY, n INTEGER)")
    setup.execute("INSERT INTO spend (k, n) VALUES ('day', 0)")
    allowed = []

    def spend():
        conn = db.connect(path, isolation_level=None)
        conn.execute("BEGIN IMMEDIATE")
        n = conn.execute("SELECT n FROM spend WHERE k = 'day'").fetchone()[0]
        _time.sleep(0.2)
        if n < 1:
            conn.execute("UPDATE spend SET n = n + 1 WHERE k = 'day'")
            allowed.append(True)
        conn.execute("COMMIT")

    threads = [threading.Thread(target=spend) for _ in range(2)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert allowed == [True]
    assert setup.execute("SELECT n FROM spend").fetchone()[0] == 1


@needs_postgres
def test_lastrowid_is_the_row_this_insert_made(tmp_path):
    conn = db.connect(str(tmp_path / "m.db"), isolation_level=None)
    conn.execute("CREATE TABLE IF NOT EXISTS m (id INTEGER PRIMARY KEY, x TEXT)")
    assert conn.execute("INSERT INTO m (id, x) VALUES (50, 'a')").lastrowid == 50
    first = conn.execute("INSERT INTO m (x) VALUES ('b')").lastrowid
    assert first not in (None, 50)


@needs_postgres
def test_default_isolation_is_one_transaction_until_commit(tmp_path):
    """Review fix: a store opened without isolation_level=None relied on
    sqlite3's implicit transaction; each statement used to commit alone."""
    path = str(tmp_path / "domains.db")
    writer = db.connect(path, timeout=10)
    writer.execute("CREATE TABLE IF NOT EXISTS domains (d TEXT PRIMARY KEY)")
    writer.execute("INSERT INTO domains (d) VALUES ('a.com')")
    writer.commit()
    with writer:
        writer.execute("DELETE FROM domains")
        writer.execute("INSERT INTO domains (d) VALUES ('b.com')")
        reader = db.connect(path, timeout=10)
        assert [r[0] for r in reader.execute("SELECT d FROM domains")] == ["a.com"], \
            "a reader saw the table half rewritten"
    assert [r[0] for r in db.connect(path).execute("SELECT d FROM domains")] == ["b.com"]
    writer.execute("INSERT INTO domains (d) VALUES ('c.com')")
    writer.rollback()
    assert db.connect(path).execute("SELECT COUNT(*) FROM domains").fetchone()[0] == 1


@needs_postgres
def test_health_asks_the_database_rather_than_assuming(tmp_path):
    db._PROBED[:] = [0.0, None]
    report = db.report()
    assert report["backend"] == "postgres" and report["reachable"] is True
    assert report["pool"]["max"] == db.max_connections()


@needs_postgres
def test_a_store_round_trips(tmp_path):
    import messages

    store = messages.MessageStore(str(tmp_path / "messages.db"))
    sent = store.send("alice", "bob", text="hello")
    assert store.latest_id("bob") == sent.id
    assert [m.text for m in store.arrived_for("bob")] == ["hello"]


@needs_postgres
def test_the_question_box_refuses_typed_sql_but_recipes_answer(tmp_path, monkeypatch):
    """SQLite's authorizer is what kept a typed question read-only and its
    secrets hidden; Postgres has no such hook, so typed SQL is not run at all.
    A recipe is SQL written in code and still answers."""
    import asyncio

    import admin_tracker

    with pytest.raises(admin_tracker.QueryError, match="Postgres"):
        admin_tracker.run_query("SELECT 1")
    with pytest.raises(admin_tracker.QueryError):
        admin_tracker.run_query("DELETE FROM accounts.accounts")
    answer = asyncio.run(admin_tracker.ask("how many accounts"))
    assert answer["source"] == "recipe" and len(answer["rows"]) == 1
