"""Option B (PROBLEMS.md §243): every store through `db.connect`.

* With no DATABASE_URL nothing changes: a store gets a sqlite3 connection.
* With one, a store's SQLite is translated to Postgres - and the parts that
  could silently change meaning (REAL timestamps, LIKE's case, INSERT OR
  REPLACE, SQLite's self-numbering row ids) are pinned here.
* Staging reaches its own private database and nothing else (the owner's
  amendment to zero-spend-staging): libpq's sockets are invisible to the
  network guard, so `db.connect` enforces it, and the guard allows exactly
  that one address for anything that does go through Python's sockets.

The round-trip tests at the bottom need a Postgres (CI's Postgres job sets
DATABASE_URL); everything above them runs anywhere.
"""
from __future__ import annotations

import os
import sqlite3
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import db  # noqa: E402
import spend_guard  # noqa: E402


def sql(statement: str, named: bool = False) -> str:
    return db.translate(statement, named)[0]


def test_without_a_database_url_a_store_gets_sqlite(monkeypatch, tmp_path):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    conn = db.connect(str(tmp_path / "x.db"), timeout=5.0, isolation_level=None)
    assert isinstance(conn, sqlite3.Connection)
    assert db.report() == {"backend": "sqlite"}


def test_timestamps_keep_their_precision():
    # Postgres' REAL is four bytes: an epoch time would round by minutes.
    assert "DOUBLE PRECISION" in sql("CREATE TABLE t (at REAL NOT NULL)")
    assert " REAL" not in sql("CREATE TABLE t (at REAL NOT NULL)")


def test_a_sqlite_row_id_still_numbers_itself():
    for ddl in ("CREATE TABLE t (id INTEGER PRIMARY KEY, x TEXT)",
                "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT)"):
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql(ddl)


def test_like_ignores_case_as_sqlite_did():
    assert sql("SELECT 1 FROM t WHERE handle LIKE ?") == \
        "SELECT 1 FROM t WHERE handle ILIKE %s"
    assert "NOT ILIKE 'g:%%'" in sql("SELECT 1 FROM t WHERE r NOT LIKE 'g:%'")
    assert sql("SELECT x FROM t ORDER BY name COLLATE NOCASE") == \
        "SELECT x FROM t ORDER BY lower(name)"


def test_placeholders_and_literals():
    assert sql("SELECT * FROM t WHERE a = ? AND b = ?") == \
        "SELECT * FROM t WHERE a = %s AND b = %s"
    assert sql("SELECT * FROM t WHERE a = :who", named=True) == \
        "SELECT * FROM t WHERE a = %(who)s"
    # A colon in a string literal is text unless the parameters are named.
    assert sql("SELECT 'a:b' FROM t WHERE x = ?") == "SELECT 'a:b' FROM t WHERE x = %s"


def test_a_scalar_max_with_a_call_inside_it():
    assert sql("UPDATE t SET f = MAX(?, CASE WHEN a THEN b ELSE 0 END), e = MAX(e, ?)") == \
        "UPDATE t SET f = GREATEST(%s, CASE WHEN a THEN b ELSE 0 END), e = GREATEST(e, %s)"
    assert sql("SELECT MAX(id), MIN(COALESCE(a, b), 3) FROM t") == \
        "SELECT MAX(id), LEAST(COALESCE(a, b), 3) FROM t"


def test_inserts_that_ignore_or_replace():
    statement, kind, table, columns = db.translate(
        "INSERT OR IGNORE INTO members (gid, user_id) VALUES (?, ?)")
    assert statement.endswith("ON CONFLICT DO NOTHING") and kind == "ignore"
    statement, kind, table, columns = db.translate(
        "INSERT OR REPLACE INTO prefs (user_id, topics) VALUES (?, ?)")
    assert kind == "replace" and table == "prefs" and columns == ("user_id", "topics")
    assert statement.startswith("INSERT INTO prefs")


def test_pragmas():
    assert db.translate("PRAGMA journal_mode=WAL")[1] == "skip"
    assert "information_schema.columns" in sql("PRAGMA table_info(usage)")
    assert "column_name AS name" in sql("PRAGMA table_info(usage)")


def test_each_store_file_is_its_own_schema():
    a = db.schema_for("/data/messages.db")
    assert a.startswith("messages_")
    assert db.schema_for("/data/social.db").split("_")[-1] == a.split("_")[-1]
    assert db.schema_for("/tmp/other/messages.db") != a


def test_the_address_is_read_from_either_form():
    assert db.host_of("postgresql://u:p@dpg-abc-a:5432/fam") == ("dpg-abc-a", 5432)
    assert db.host_of("host=/tmp port=5433 user=postgres") == ("/tmp", 5433)
    assert db.host_of("") == ("", 0)


def test_staging_refuses_a_public_database(monkeypatch):
    monkeypatch.setattr(spend_guard, "enabled", lambda: True)
    monkeypatch.setattr(db, "_resolves_private", lambda host: host == "dpg-private-a")
    db.check_staging_address("postgresql://u:p@dpg-private-a/fam")
    with pytest.raises(db.DatabaseRefused):
        db.check_staging_address("postgresql://u:p@db.example.com/fam")


def test_production_is_not_held_to_staging_s_rule(monkeypatch):
    monkeypatch.setattr(spend_guard, "enabled", lambda: False)
    monkeypatch.setattr(db, "_resolves_private", lambda host: False)
    db.check_staging_address("postgresql://u:p@db.example.com/fam")


def test_the_guard_allows_exactly_the_one_private_database(monkeypatch):
    monkeypatch.setattr(spend_guard, "_DATABASE", {("10.0.0.7", 5432)})
    assert spend_guard._is_local(("10.0.0.7", 5432))
    assert not spend_guard._is_local(("10.0.0.7", 5433)), "another port on it"
    assert not spend_guard._is_local(("10.0.0.8", 5432)), "a neighbour"
    assert not spend_guard._is_local(("93.184.216.34", 443))


def test_a_public_database_is_not_allowed_by_the_guard(monkeypatch):
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@db.example.com:5432/fam")
    monkeypatch.setattr(db, "_resolves_private", lambda host: False)
    assert spend_guard._database_addresses() == set()


# -------------------------------------------------- against a real Postgres

needs_postgres = pytest.mark.skipif(not db.enabled(),
                                    reason="no DATABASE_URL (CI's Postgres job sets one)")


@needs_postgres
def test_a_replace_is_an_upsert_on_the_key(tmp_path):
    conn = db.connect(str(tmp_path / "prefs.db"))
    conn.execute("CREATE TABLE IF NOT EXISTS prefs (user_id TEXT PRIMARY KEY,"
                 " topics TEXT NOT NULL DEFAULT '', at REAL)")
    conn.execute("INSERT OR REPLACE INTO prefs (user_id, topics, at) VALUES (?, ?, ?)",
                 ("u1", "nfl", 1791600000.25))
    conn.execute("INSERT OR REPLACE INTO prefs (user_id, topics, at) VALUES (?, ?, ?)",
                 ("u1", "nba", 1791600001.75))
    rows = conn.execute("SELECT user_id, topics, at FROM prefs").fetchall()
    assert [tuple(r) for r in rows] == [("u1", "nba", 1791600001.75)]
    assert rows[0]["topics"] == "nba"


@needs_postgres
def test_a_failed_statement_does_not_poison_the_next(tmp_path):
    conn = db.connect(str(tmp_path / "t.db"))
    conn.execute("CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY, x TEXT UNIQUE)")
    conn.execute("BEGIN")
    conn.execute("INSERT INTO t (x) VALUES (?)", ("a",))
    with pytest.raises(sqlite3.IntegrityError):
        conn.execute("INSERT INTO t (x) VALUES (?)", ("a",))
    # SQLite would carry on; Postgres refuses until a rollback, which the
    # connection does itself.
    assert conn.execute("SELECT COUNT(*) FROM t").fetchone()[0] == 0
    cur = conn.execute("INSERT INTO t (x) VALUES (?)", ("b",))
    assert cur.lastrowid is not None


@needs_postgres
def test_a_store_round_trips(tmp_path):
    import messages

    store = messages.MessageStore(str(tmp_path / "messages.db"))
    sent = store.send("alice", "bob", text="hello")
    assert store.latest_id("bob") == sent.id
    assert [m.text for m in store.arrived_for("bob")] == ["hello"]


@needs_postgres
def test_the_question_box_refuses_typed_sql_but_recipes_answer(tmp_path, monkeypatch):
    """SQLite's authorizer is what kept a typed question read-only and its
    secrets hidden; Postgres has no such hook, so typed SQL is not run at all.
    A recipe is SQL written in code and still answers."""
    import asyncio

    import admin_tracker

    with pytest.raises(admin_tracker.QueryError, match="Postgres"):
        admin_tracker.run_query("SELECT 1")
    with pytest.raises(admin_tracker.QueryError):
        admin_tracker.run_query("DELETE FROM accounts.accounts")
    answer = asyncio.run(admin_tracker.ask("how many accounts"))
    assert answer["source"] == "recipe" and len(answer["rows"]) == 1
