"""Write PROBLEMS_INDEX.md: one line per PROBLEMS.md section, with its line.

PROBLEMS.md is over 700 KB, so finding one section by searching it costs more
than the section itself. The index is the table of contents it never had:
read it, then read the section by offset. It is derived, never hand-written -
`tests/test_claude_md.py` fails when it is stale, because an index that has
drifted from its file sends a reader to the wrong line with confidence.

    python tools/problems_index.py          # rewrite the index
    python tools/problems_index.py --check  # exit 1 if it is stale

Section numbers are not unique (there are two §64s and two §65s), which is why
every row carries its line number: that, not the number, is the address.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "PROBLEMS.md"
INDEX = ROOT / "PROBLEMS_INDEX.md"


def render(text: str) -> str:
    lines = text.split("\n")
    heads = [(n, line[3:].strip()) for n, line in enumerate(lines, 1)
             if line.startswith("## ")]
    rows = []
    for i, (n, title) in enumerate(heads):
        end = heads[i + 1][0] - 1 if i + 1 < len(heads) else len(lines)
        rows.append(f"| {n} | {end - n + 1} | {title.replace('|', '/')} |")
    return (
        "# PROBLEMS.md index\n\n"
        "Generated by `python tools/problems_index.py` - do not edit by hand.\n"
        "Newest last. To read a section: `Read PROBLEMS.md` with `offset` = Line\n"
        "and `limit` = Lines.\n\n"
        "| Line | Lines | Section |\n|---:|---:|---|\n"
        + "\n".join(rows) + "\n"
    )


def main() -> int:
    wanted = render(SOURCE.read_text())
    if "--check" in sys.argv[1:]:
        if not INDEX.exists() or INDEX.read_text() != wanted:
            print("PROBLEMS_INDEX.md is stale: run python tools/problems_index.py")
            return 1
        print("PROBLEMS_INDEX.md is current")
        return 0
    INDEX.write_text(wanted)
    print(f"wrote {INDEX.name}: {wanted.count(chr(10) + '| ') - 1} sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
